### ISSUE TITLE
User can randomize a restaurant to eat from

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/grub-roulette#1]
## 💰 Feature

User can generate a random restaurant to eat from

## 🗒️ Notes

This will require me to use 

## 🖼 Wireframe
![Home Page](https://user-images.githubusercontent.com/69335064/102939341-f7cfb300-4462-11eb-971f-ee700b7a7f6d.png)
![Roulette Result](https://user-images.githubusercontent.com/69335064/102939547-51d07880-4463-11eb-8e0e-78da57d4a221.png)

## ✅ Tasks

- [x] Clone repo
- [x] Link fontawesome - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css
- [x] npm install dependencies, devDependencies, and bootstrap
- [x] Save images used for figma to final project directory
- [x] Create home page header
- [x] Create navigation bar 
- [x] Create body content 
- [x] Set up server to grab restaurant data list from server
- [x] Select random restaurant from list retrieved from server
- [x] Test with HTTPie
- [x] Set up database
- [x] Create functionality for randomization to grab one restaurant data to send to database
- [x] Create page for randomized restaurant data and hash route
- [x] Move API key to .env file
- [x] Remove unnecessary packages and code
- [x] Don't involve database when generating a random restaurant for /api/random route
- [x] Change JSX so that it renders restaurant data from /api/random
- [x] Research more bootstrap and utilize it to remove as much CSS as possible
- [x] Need to create another route to retrieve store hours
- [x] Add additional information to roulette result (location, hours, etc.)
- [x] Change index.html relative links back to original state
- [x] Refactor code utilizing map function where applicable
