### ISSUE TITLE
User can input a location 

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/grub-roulette#16]
## 💰 Feature

User can see how far a restaurant is from the user's input location

## 🗒️ Notes

This will require me to use ...

## 🖼 Wireframe
![Home Page](https://user-images.githubusercontent.com/69335064/103693569-5bbba680-4f4e-11eb-81dd-468a62b79dea.png)

## ✅ Tasks

- [x] Touch up on geolocation and google maps api
- [x] User can allow access to current location
- [x] Create location search bar component
- [x] Create route to accept address as part of search result
- [x] Test with HTTPie
- [x] Integrate route with React component
