### ISSUE TITLE
User can see history of previous randomizations

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/grub-roulette#2]
## 💰 Feature

User will be able to see previously generated randomizations

## 🗒️ Notes

This will require me to use ...

## 🖼 Wireframe

![Roulette History](https://user-images.githubusercontent.com/69335064/102939798-cacfd000-4463-11eb-8718-684028339c62.png)

## ✅ Tasks

- [x] Setup/clean database
- [x] Adjust /api/random route to post selected random restaurant to the database
- [x] Test with HTTPie
- [x] Create page for to render roulette history from database
