### ISSUE TITLE
User can view google maps

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/grub-roulette#7]
## 💰 Feature

User can view google maps API based on lat and longitude

## 🗒️ Notes

This will require me to use 

## 🖼 Wireframe
![Roulette Result](https://user-images.githubusercontent.com/69335064/102940676-b7bdff80-4465-11eb-89ce-9aee728fc146.png)
![Home Page](https://user-images.githubusercontent.com/69335064/103838236-686cf700-5041-11eb-9fbe-92f953cb8ba1.png)

## ✅ Tasks

- [x] Use npm google-maps-react to display map on restaurant page
- [x] Set up JavaScript geolocation API to track current location
- [x] Generate map on home page
- [x] Add markers for both restaurant and user location
