### ISSUE TITLE
User can favorite restaurants

### ISSUE THREAD

**Issue by DeanVo** [DeanVo/grub-roulette#8]
## 💰 Feature

User can save resulting restaurant as a favorite

## 🗒️ Notes

This will require me to use 

## 🖼 Wireframe
![Favorited Restaurants](https://user-images.githubusercontent.com/69335064/102940776-efc54280-4465-11eb-90d5-d30666be5e6b.png)
![Roulette Result](https://user-images.githubusercontent.com/69335064/102940780-f0f66f80-4465-11eb-85c0-881eadaac2c6.png)

## ✅ Tasks

- [x] Create top bar component
- [x] Check database to ensure it accepts favorites
- [x] Create route for favorites component to post to DB
- [x] Test with HTTPie
- [x] Create route for favorites component to delete from DB
- [x] Test with HTTPie
- [x] Integrate favorite icon on toggle to add and remove selected restaurant to and from the database
